baseURL: "https://kyzy540.github.io/"
languageCode: "en-us"
title: "ä½è´¨é‡éšç¬”"
theme: "hugo-PaperMod"

markup:
    goldmark:
        renderer:
            unsafe: true

menu:
    main:
        - name: tags
          url: tags/

params:
    homeInfoParams:
        Content: "ä¸»è§‚ï¼Œä¸è´Ÿè´£ï¼Œå›¾ä¸€ä¹ [ğŸ’¬](/post/githubpage_blog_guide)"