baseURL: "https://kyzy540.github.io/"
languageCode: "en-us"
title: "ä½è´¨é‡éšç¬”"
theme: "hugo-PaperMod"

enableInlineShortcodes: true

markup:
    goldmark:
        renderer:
            unsafe: true

menu:
    main:
        - name: Tags
          url: tags/
          weight: 1
        - name: Archive
          url: archives/
          weight: 2
        - name: Search
          url: search/
          weight: 3

params:
    ShowCodeCopyButtons: true
    homeInfoParams:
        Content: "ä¸»è§‚ï¼Œä¸è´Ÿè´£ï¼Œå›¾ä¸€ä¹ [ğŸ’¬](/post/githubpage_blog_guide)"

outputs:
    home:
        - HTML
        - RSS
        - JSON